version: '2'
services:
    jhipstersampleapplicationgateway-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleApplicationGateWay/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterSampleApplicationGateWay
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
